version: "3.9"

services:
  timecase:
    container_name: timecase-backend
    restart: unless-stopped
    image: timecase-test  # Your locally built image
    ports:
      - "9000:80"  # Expose the app on port 9000 of your host
    volumes:
      - ./timecase:/var/www/html  # Bind the current directory to the container's /var/www/html
    depends_on:
      - db  # Make sure the database starts first
    tty: true
    networks:
      - timecase-network

  db:
    container_name: timecase-db
    image: mysql:5.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    volumes:
      - ./dbdata:/var/lib/mysql  # Persist database data
    networks:
      - timecase-network

networks:
  timecase-network:
    driver: bridge